import { Links } from '@/_components/links';
import '@/app/home/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <section style={{ padding: "1rem" }}> <small>Master Header </small> | &nbsp;
         <Links />
        </section>
        <br />
        <>
          {children}
        </>
      </body>
    </html>
  )
}
