name: Build and Deploy app

on:
  push:
    branches:
      - dev
      
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose deployment environment"
        options:
          - dev
          - acc
          - tst
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    #environment: ${{ inputs.env }}
    steps:
      - name: Show selected environment
        run: echo "The selected environment: ${{ inputs.env }}"
